name: QuestSystem
version: '${project.version}'
main: de.rjst.questsystem.QuestSystem
api-version: '1.20'
author: RStenzhorn
website: https://github.com/RStenzhorn

dependencies:
  server:
    Vault:
      load: OMIT
      required: true
      join-classpath: true

commands:
  quest:
  questReward:
